sal-scripts/sal/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^login/$', 'django.contrib.auth.views.login'),
    url(r'^logout/$', 'django.contrib.auth.views.logout_then_login'),
    url(r'^changepassword/$', 'django.contrib.auth.views.password_change'),
    url(r'^changepassword/done/$', 'django.contrib.auth.views.password_change_done'),
   	url(r'^', include('server.urls')),
    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    #url(r'^$', 'namer.views.index', name='home'),

)
if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()

if 'config' in settings.INSTALLED_APPS:
    config_pattern = patterns('',
    url(r'^config/', include('config.urls'))
    )
    urlpatterns += config_pattern

sal-scripts/server/urls.py
from django.conf.urls import *

urlpatterns = patterns('server.views',
    #front page
    url(r'^$', 'index', name='home'),
    # BU Dashboard
    url(r'^dashboard/(?P<bu_id>.+)/', 'bu_dashboard', name='bu_dashboard'),
    # Overview List (Group)
    #url(r'^machinegroup/overview/(?P<group_id>.+)/(?P<req_type>.+)/(?P<data>.+)/$', 'overview_list_group', name='overview_list_group'),
    # Overview List (Group)
    #url(r'^bu/overview/(?P<req_type>.+)/(?P<data>.+)/(?P<bu_id>.+)/$', 'overview_list_all', name='overview_list_bu'),
    # Overview List (All)
    #url(r'^overview/(?P<req_type>.+)/(?P<data>.+)/$', 'overview_list_all', name='overview_list_all'),
    # Machine List (front page)
    url(r'^list/(?P<pluginName>.+)/(?P<data>.+)/$', 'machine_list', name='machine_list_front'),
    
    # Machine List (id)
    url(r'^id_list/(?P<pluginName>.+)/(?P<data>.+)/(?P<page>.+)/(?P<theID>.+)/$', 'machine_list', name='machine_list_id'),
    # Group Dashboard
    url(r'^machinegroup/(?P<group_id>.+)/', 'group_dashboard', name='group_dashboard'),
    # Machine detail
    url(r'^machine_detail/(?P<machine_id>.+)/', 'machine_detail', name='machine_detail'),
    # Delete Machine
    url(r'^machine/delete/(?P<machine_id>.+)/', 'delete_machine', name='delete_machine'),
    # checkin
    url(r'^checkin', 'checkin', name='checkin'),
    # New Business Unit
    url(r'^new-bu/', 'new_business_unit', name='new_business_unit'),
    # New Machine Group
    url(r'^new-machine-group/(?P<bu_id>.+)/', 'new_machine_group', name='new_machine_group'),
    # Edit Machine Group
    url(r'^edit-machine-group/(?P<group_id>.+)/', 'edit_machine_group', name='edit_machine_group'),
)

sal-scripts/server/models.py
from django.db import models
from django.contrib.auth.models import User
import random
import string
import plistlib
from xml.parsers.expat import ExpatError
import base64
import bz2
from datetime import datetime

# def id_generator(size=6, chars=string.ascii_uppercase + string.digits):
# ...    return ''.join(random.choice(chars) for x in range(size))
def GenerateKey():
    key = ''.join(random.choice(string.ascii_lowercase + string.digits) for x in range(128))
    try:
        MachineGroup.objects.get(key=key)
        return GenerateKey()
    except MachineGroup.DoesNotExist:
        return key;
class UserProfile(models.Model):
    user = models.OneToOneField(User, unique=True)

    LEVEL_CHOICES = (
        ('SO', 'Stats Only'),
        ('RO', 'Read Only'),
        ('RW', 'Read Write'),
        ('GA', 'Global Admin'),
    )
    level = models.CharField(max_length=2, choices=LEVEL_CHOICES, default='SO')
User.userprofile = property(lambda u: UserProfile.objects.get_or_create(user=u)[0])

class BusinessUnit(models.Model):
    name = models.CharField(max_length=100)
    users = models.ManyToManyField(User)
            
    def __unicode__(self):
        return self.name
    class Meta:
        ordering = ['name']

class MachineGroup(models.Model):
    business_unit = models.ForeignKey(BusinessUnit)
    name = models.CharField(max_length=100)
    key = models.CharField(max_length=255, unique=True, blank=True, null=True, editable=False)
    def save(self):
            if not self.id:
                self.key = GenerateKey()
            super(MachineGroup, self).save()
    def __unicode__(self):
        return self.name
    class Meta:
        ordering = ['name']
    
class Machine(models.Model):
    OS_CHOICES = (
        ('Darwin', 'OS X'),
        ('Windows', 'Windows'),
        ('Linux', 'Linux'),
    )
    machine_group = models.ForeignKey(MachineGroup)
    serial = models.CharField(max_length=100, unique=True)
    hostname = models.CharField(max_length=256, null=True, blank=True)
    operating_system = models.CharField(max_length=256)
    memory = models.CharField(max_length=256, null=True, blank=True)
    memory_kb = models.IntegerField(default=0)
    munki_version = models.CharField(max_length=256, null=True, blank=True)
    manifest = models.CharField(max_length=256)
    hd_space = models.CharField(max_length=256, null=True, blank=True)
    hd_total = models.CharField(max_length=256, null=True, blank=True)
    hd_percent = models.CharField(max_length=256, null=True, blank=True)
    console_user = models.CharField(max_length=256, null=True, blank=True)
    machine_model = models.CharField(max_length=256, null=True, blank=True)
    cpu_type = models.CharField(max_length=256, null=True, blank=True)
    cpu_speed = models.CharField(max_length=256, null=True, blank=True)
    os_family = models.CharField(max_length=256, choices=OS_CHOICES, verbose_name="OS Family", default="Darwin")
    last_checkin = models.DateTimeField(blank=True,null=True)
    report = models.TextField(editable=True, null=True)
    errors = models.IntegerField(default=0)
    warnings = models.IntegerField(default=0)
    activity = models.TextField(editable=False, null=True, blank=True)
    puppet_version = models.TextField(null=True, blank=True)
    last_puppet_run = models.DateTimeField(blank=True,null=True)
    puppet_errors = models.IntegerField(default=0)
        
    def encode(self, plist):
        string = plistlib.writePlistToString(plist)
        bz2data = bz2.compress(string)
        b64data = base64.b64encode(bz2data)
        return b64data
        
    def decode(self, data):
        # this has some sucky workarounds for odd handling
        # of UTF-8 data in sqlite3
        try:
            plist = plistlib.readPlistFromString(data)
            return plist
        except:
            try:
                plist = plistlib.readPlistFromString(data.encode('UTF-8'))
                return plist
            except:
                try:
                    return self.b64bz_decode(data)
                except:
                    return dict()
        
    def b64bz_decode(self, data):
        try:
            bz2data = base64.b64decode(data)
            string = bz2.decompress(bz2data)
            plist = plistlib.readPlistFromString(string)
            return plist
        except Exception:
            return {}
        
    def get_report(self):
        return self.decode(self.report)
        
    def get_activity(self):
        return self.decode(self.activity)
        
    def update_report(self, base64bz2report):
        # Save report.
        try:
            base64bz2report = base64bz2report.replace(" ", "+")
            plist = self.b64bz_decode(base64bz2report)
            #self.report = base64bz2report
            self.report = plistlib.writePlistToString(plist)
        except:
            plist = None
            self.report = ''

        if plist is None:
            self.activity = None
            self.errors = 0
            self.warnings = 0
            self.console_user = "<None>"
            return
        
        # Check activity.
        activity = dict()
        for section in ("ItemsToInstall",
                        "InstallResults",
                        "ItemsToRemove",
                        "RemovalResults",
                        "AppleUpdates"):
            if (section in plist) and len(plist[section]):
                activity[section] = plist[section]
        if activity:
            #self.activity = self.encode(activity)
            self.activity = plistlib.writePlistToString(activity)
        else:
            self.activity = None
        
        # Check errors and warnings.
        if "Errors" in plist:
            self.errors = len(plist["Errors"])
        else:
            self.errors = 0
        
        if "Warnings" in plist:
            self.warnings = len(plist["Warnings"])
        else:
            self.warnings = 0
        
        # Check console user.
        self.console_user = "unknown"
        if "ConsoleUser" in plist:
            self.console_user = unicode(plist["ConsoleUser"])
    def __unicode__(self):
        return self.hostname
    class Meta:
        ordering = ['hostname']
class Fact(models.Model):
    machine = models.ForeignKey(Machine)
    fact_name = models.TextField()
    fact_data = models.TextField()
    def __unicode__(self):
        return self.fact_name
    class Meta:
        ordering = ['fact_name']

class HistoricalFact(models.Model):
    machine = models.ForeignKey(Machine)
    fact_name = models.TextField()
    fact_data = models.TextField()
    fact_recorded = models.DateTimeField(db_index=True)
    def __unicode__(self):
        return self.fact_name
    class Meta:
        ordering = ['fact_name', 'fact_recorded']

class Condition(models.Model):
    machine = models.ForeignKey(Machine)
    condition_name = models.TextField()
    condition_data = models.TextField()
    def __unicode__(self):
        return self.condition_name
    class Meta:
        ordering = ['condition_name']
        
class PendingUpdate(models.Model):
    machine = models.ForeignKey(Machine)
    update = models.CharField(max_length=256, null=True, blank=True)
    update_version = models.CharField(max_length=256, null=True, blank=True)
    display_name = models.CharField(max_length=256, null=True, blank=True)
    def __unicode__(self):
        return self.update
    class Meta:
        ordering = ['display_name']
        unique_together = ("machine", "update")
    
class PendingAppleUpdate(models.Model):
    machine = models.ForeignKey(Machine)
    update = models.CharField(max_length=256, null=True, blank=True)
    update_version = models.CharField(max_length=256, null=True, blank=True)
    display_name = models.CharField(max_length=256, null=True, blank=True)
    def __unicode__(self):
        return self.update
    class Meta:
        ordering = ['display_name']
        unique_together = ("machine", "update")

sal-scripts/server/forms.py
from django import forms
from models import *

class BusinessUnitForm(forms.ModelForm):
    class Meta:
        model = BusinessUnit
        widgets = {'users': forms.CheckboxSelectMultiple}
    def __init__(self, *args, **kwargs):
        super(BusinessUnitForm, self).__init__(*args, **kwargs)
        self.fields['users'].help_text = ''
        
class MachineGroupForm(forms.ModelForm):
    class Meta:
        model = MachineGroup
        fields = ('name',)

class EditMachineGroupForm(forms.ModelForm):
    class Meta:
        model = MachineGroup
        fields = ('name',)

# class UserToBU(forms.ModelForm):
#     bus = forms.ModelMultipleChoiceField(
#         queryset=Entry.objects.all(),
#         widget=forms.CheckboxSelectMultiple)

#     class Meta:
#         model = BusinessUnit

#     def __init__(self, *args, **kwargs):
#         super(BlogForm, self).__init__(*args, **kwargs)
#         if self.instance:
#             entries = Entry.objects.filter(blog=blog)
#             self.fields['entries'].queryset = entries

sal-scripts/server/templates/server/bu_dashboard.html
{% extends "base.html" %}
{% load i18n %}
{% load dashboard_extras %}
{% block script %}

{% endblock %}

{% block nav %}

    {% if user.userprofile.level == 'GA' %}
            <li><a href="{% url 'home' %}"><i class="fa fa-chevron-left fa-fw"></i> Back</a></li>
    {% endif %}
    <li class="active">
        <a href="#"><i class="fa fa-building fa-fw"></i> {{business_unit}}<span class="fa arrow"></span></a>
        <ul class="nav nav-second-level">
            {% for machine_group in business_unit.machinegroup_set.all %}
                <li><a href="{% url 'group_dashboard' machine_group.id %}">{{ machine_group.name }}
                    <span class="badge badge-info pull-right">
                        {{ machine_group.machine_set.count }}
                    </span>
                    </a>
                </li>
            {% endfor %}
            {% if is_editor %}
            {% if CONFIG_INSTALLED %}
                <li><a href="{% url 'config_business_unit_index' business_unit.id %}"><i class="fa fa-wrench fa-fw"></i>  Configure Business Unit</a></li>
                {% if machine_groups.count > 0 %}
                <li><a href="{% url 'config_new_machine' business_unit.id %}"><i class="fa fa-plus fa-fw"></i> New Machine</a></li>
                {% endif %}
            {% endif %}
            <li><a href="{% url 'new_machine_group' business_unit.id %}"><i class="fa fa-plus fa-fw"></i> New Machine Group</a></li>
            {% endif %}
        </ul>
        <!-- /.nav-second-level -->
    </li>

{% endblock %}
{% block content %}
<div class="row">
    <div class="col-md-4">
        <h3>{{ business_unit.name }}</h3>
    </div>
</div>

{% if machine_groups.count > 0 %}

<div class="row">
    {% for widget in output %}
    {{ widget.html|safe }}
    {% endfor %}
</div>
<div class="row">
    {% if pending_updates|length %}
    <div class="col-md-4">
        <legend>Pending 3rd Party Updates</legend>
            <table class="table table-striped table-condensed table-bordered">
            {% for item in pending_updates|dictsort:'update' %}
                <tr>
                    <td>
                        <a href="{% url 'overview_list_bu' 'pending_updates' item.update business_unit.id %}">
                        {{ item.display_name }} {{ item.update_version }}
                        <span class="badge pull-right">{{ item.count }}</span>
                        </a>
                    </td>
                </tr>
            {% endfor %}
            </table>
    </div>
    {% endif %}
    
    {% if pending_apple_updates|length %}
    <div class="col-md-4">
        <legend>Pending Apple Updates</legend>
            <table class="table table-striped table-condensed table-bordered">
            {% for item in pending_apple_updates|dictsort:'update' %}
                <tr>
                    <td>
                        <a href="{% url 'overview_list_bu' 'pending_apple_updates' item.update business_unit.id %}">
                        {{ item.display_name }} {{ item.update_version }}
                        <span class="badge pull-right">{{ item.count }}</span>
                        </a>
                    </td>
                </tr>
            {% endfor %}
            </table>
    </div>
    {% endif %}
</div>
{% else %}No Machine groups configured.{% endif %}

{% endblock %}

sal-scripts/server/templates/server/group_dashboard.html
{% extends "base.html" %}
{% load i18n %}
{% load dashboard_extras %}
{% block script %}

{% endblock %}

{% block nav %}
<li> <a href="{% url 'bu_dashboard' business_unit.id %}"><i class="fa fa-fw fa-chevron-left"></i> Back</a></li>

    <li class="active">
        <a href="#"><i class="fa fa-building fa-fw"></i> {{business_unit}}<span class="fa arrow"></span></a>
        <ul class="nav nav-second-level">
            {% for group in business_unit.machinegroup_set.all %}
                <li class="active"><a href="{% url 'group_dashboard' group.id %}">{{ group.name }}
                    <span class="badge badge-info pull-right">
                        {{ group.machine_set.count }}
                    </span>
                    </a>
                </li>
            {% endfor %}
            {% if user.userprofile.level == 'GA' or user.userprofile.level == 'RW' %}
        {% if CONFIG_INSTALLED %}
            <li><a href="{% url 'config_machine_group_index' machine_group.id %}"><i class="fa fa-wrench fa-fw"></i> Configure Group</a></li>
        {% endif %}
        <li><a href="{% url 'edit_machine_group' machine_group.id %}"><i class="fa fa-fw fa-pencil"></i> Rename Group</a></li>
    {% endif %}
        </ul>
        <!-- /.nav-second-level -->
    </li>
    
{% endblock %}
{% block content %}
<div class="row">
    <div class="col-md-12">
        <h3>{{ machine_group.name }}</h3>
        {% if user_level == "GA" %}
        <legend>Key</legend>
        <pre class="scrollable">{{ machine_group.key }}</pre>
        {% endif %}
    </div>
</div>

<div class="row">
    {% for widget in output %}
    {{ widget.html|safe }}
    {% endfor %}
</div>
</div>


{% endblock %}

sal-scripts/server/templates/server/index.html
{% extends "base.html" %}
{% load i18n %}
{% load dashboard_extras %}

{% block script %}


{% endblock %}

{% block nav %}
    {% if user.userprofile.level == 'GA' or user.userprofile.level == 'RW' %}
        {% if CONFIG_INSTALLED %}
            {% if user.userprofile.level == 'GA' %}
                <li><a href="{% url 'config_index' %}"><i class="fa fa-wrench fa-fw"></i> Configure Machines</a></li>
            {% endif %}
        {% endif %}
    {% endif %}
    <li class="active">
        <a href="#"><i class="fa fa-building fa-fw"></i> Business Units<span class="fa arrow"></span></a>
        <ul class="nav nav-second-level">
            {% for business_unit in business_units.all %}
                <li><a href="{% url 'bu_dashboard' business_unit.id %}">{{ business_unit.name }}
                    <span class="badge badge-info pull-right">
                        {{ business_unit.id|bu_machine_count }}
                    </span>
                    </a>
                </li>

            {% endfor %}
            {% if user.userprofile.level == 'GA' %}
        <li><a href="{% url 'new_business_unit' %}"><i class="fa fa-plus fa-fw"></i> New Business Unit</a></li>
    {% endif %}
        </ul>
        <!-- /.nav-second-level -->
    </li>
    
{% endblock %}
{% block content %}

<div class="row">
    {% for widget in output %}
    {{ widget.html|safe }}
    {% endfor %}
</div>

{% endblock %}

sal-scripts/server/templates/server/no_access.html
{% extends "base.html" %}
{% load i18n %}
{% load dashboard_extras %}

{% block script %}


{% endblock %}


{% block content %}

<div class="row">
    <div class="col-md-10"><div class="alert alert-danger">You haven't been given access to any Business Units. Contact your administrator to be given access.</div></div>
</div>

{% endblock %}

sal-scripts/server/templates/server/overview_list_all.html
{% extends "base.html" %}
{% load i18n %}
{% load dashboard_extras %}
{% block script %}
<script type="text/javascript" charset="utf-8">
    $(document).ready(function() {
        $('.groupList').dataTable({
            //"sDom": "<'row'<'span6'l><'span6'f>r>t<'row'<'span6'i><'span6'p>>",
            // "iDisplayLength": 20,
            "aLengthMenu": [[20, 50, -1], [20, 50, "All"]],
            // "sPaginationType": "bootstrap",
            // "bStateSave": true,
            // "aaSorting": [[1,'asc']]
        });
    } );
</script>

{% endblock %}

{% block nav %}
<li><a href="{{ request.META.HTTP_REFERER }}"><i class="fa fa-fw fa-chevron-left"></i> Back</a></li>
{% endblock %}
{% block content %}

<div class="panel panel-default">
{% if title %}
    <div class="panel-heading">
        {{ title }}
    </div>
{% endif %}
<div class="panel-body">
    <div class="table-responsive">
        <table class="groupList table table-striped table-condensed">
            <thead>
                <tr>
                  <th>Machine</th>
                  <th>User</th>
                  <th>Latest Run</th>
                </tr>
            </thead>
            <tbody>
                {% for item in machines.all|dictsort:'hostname' %}
                <tr>
                    <td>
                        <a href="{% url 'machine_detail' item.id %}">
                        {% if item.hostname %}
                            {{ item.hostname }}
                        {% else %}
                            {{ item.serial }}
                        {% endif %}
                        </a>
                    </td>

                    <td>{{ item.console_user }}</td>
                    <td>{{ item.last_checkin|date:"Y-m-d H:i" }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    </div>
</div>
{% endblock %}

sal-scripts/server/templates/server/pkgtable.html
{% load dashboard_extras %}
{% if pkglist|length %}
  
  <table class="client_info table table-striped table-condensed">
    <thead>
      <tr>
        <th>Name</th>
        <th>Size</th>
        <th>Status</th>
      </tr>
    </thead>
    <tbody>
      {% for item in pkglist|dictsort:"display_name" %}
      <tr>
        <td>
          {% if item.display_name|length %}
            {{ item.display_name }}
          {% else %}
            {{ item.name }}
          {% endif %}
          {{ item.version_to_install }}
          {{ item.installed_version }}
        </td>
        <td>
          {{ item.installed_size|humanreadablesize }} 
       </td>
        <td>
          {% if 'install_result' in item %}
            {{ item.install_result }}
          {% else %}
            {% if item.installed %}
              installed
            {% else %}
              <span class='error'>not installed</span>
            {% endif %}
          {% endif %}
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
{% endif %}